use std::{collections::HashSet, path::PathBuf};

use nucleo_matcher::{Config as MatcherConfig, Matcher};
use ratatui::widgets::ListState;

use crate::event::EventHandler;

use super::{
    super::{
        ActivePane, App, BranchCompareField, ReviewMode,
        diff::{DiffViewCache, DiffViewport},
    },
    LaunchPreference,
};

impl App {
    pub(super) fn build_base_app(
        repo_root: PathBuf,
        chooser_file_path: Option<PathBuf>,
        events: EventHandler,
        preference: LaunchPreference,
    ) -> Self {
        Self {
            running: true,
            repo_root,
            chooser_file_path,
            repo_error: None,
            repo_loading: false,
            events,
            active_pane: ActivePane::Sidebar,
            review_mode: ReviewMode::WorkingTree,
            files: Vec::new(),
            loaded_files: Vec::new(),
            file_exclude_suffixes: super::super::file_filter::ExcludeSuffixes::from_parts(
                preference.exclude_file_suffixes,
            ),
            sidebar_items: Vec::new(),
            collapsed_directories: HashSet::new(),
            sidebar_state: ListState::default(),
            sidebar_scroll: 0,
            sidebar_viewport_height: 0,
            sidebar_hidden: false,
            selected_sidebar_row: 0,
            selected_file_index: 0,
            diff_view: Default::default(),
            diff_view_mode: preference.diff_view_mode,
            diff_line_wrap_mode: preference.diff_line_wrap_mode,
            diff_scroll: 0,
            selected_diff_line_index: 0,
            diff_text_selection: None,
            diff_text_selection_anchor: None,
            repo_request_id: 0,
            diff_request_id: 0,
            diff_load_task: None,
            diff_highlight_task: None,
            diff_highlight_job: None,
            diff_highlight_complete: false,
            diff_viewport: None::<DiffViewport>,
            background_tasks: Vec::new(),
            diff_prefetch_task: None,
            diff_prefetch_direction: Default::default(),
            diff_prefetch_anchor_file_index: None,
            review_diff_stream_index: None,
            review_diff_text_index: None,
            review_diff_snapshot: None,
            review_diff_snapshot_request_id: 0,
            review_diff_snapshot_task: None,
            review_diff_stats: None,
            review_diff_stats_error: None,
            review_diff_stats_request_id: 0,
            review_diff_stats_task: None,
            diff_view_cache: DiffViewCache::default(),
            diff_cache_generation: 0,
            pending_diff_cache_key: None,
            highlight_registry: None,
            highlight_registry_loading: false,
            repo_watcher: None,
            repo_watcher_loading: false,
            blame_modal_open: false,
            blame_target: None,
            blame_loading: false,
            blame_details: None,
            blame_error: None,
            blame_scroll: 0,
            blame_request_id: 0,
            blame_load_task: None,
            diff_stats_modal_open: false,
            help_modal_open: false,
            theme_modal_open: false,
            theme_modal_query: String::new(),
            theme_modal_selected_index: 0,
            theme_modal_initial_name: preference.theme_name.clone(),
            theme_modal_initial_mode: preference.theme_mode,
            theme_name: preference.theme_name,
            theme_mode: preference.theme_mode,
            theme_matcher: Matcher::new(MatcherConfig::DEFAULT),
            file_filter_modal_open: false,
            file_filter_query: String::new(),
            file_search_modal_open: false,
            file_search_query: String::new(),
            file_search_selected_index: 0,
            file_search_initial_path: None,
            file_search_matcher: Matcher::new(MatcherConfig::DEFAULT),
            find_prefix_pending: false,
            diff_search_modal_open: false,
            diff_search_query: String::new(),
            diff_search_loading: false,
            diff_search_error: None,
            diff_search_results: Default::default(),
            diff_search_selected_index: 0,
            diff_search_mode: Default::default(),
            diff_search_index: None,
            diff_search_index_readiness: None,
            diff_search_index_error: None,
            diff_search_index_request_id: 0,
            diff_search_query_request_id: 0,
            diff_search_load_task: None,
            diff_search_query_task: None,
            diff_search_query_cancel_token: None,
            pending_diff_search_target: None,
            commit_search_modal_open: false,
            commit_search_query: String::new(),
            commit_search_entries: Vec::new(),
            commit_search_loading: false,
            commit_search_error: None,
            commit_search_selected_index: 0,
            commit_search_matcher: Matcher::new(MatcherConfig::DEFAULT),
            commit_search_index: Default::default(),
            branch_compare_modal_open: false,
            branch_compare_loading: false,
            branch_compare_error: None,
            branch_compare_active_field: BranchCompareField::Source,
            branch_compare_available_refs: Vec::new(),
            branch_compare_source_query: String::new(),
            branch_compare_destination_query: String::new(),
            branch_compare_source_ref: None,
            branch_compare_destination_ref: None,
            branch_compare_selected_source_index: 0,
            branch_compare_selected_destination_index: 0,
            branch_compare_matcher: Matcher::new(MatcherConfig::DEFAULT.match_paths()),
            branch_compare_ref_index: Default::default(),
            branch_merge_target: None,
            branch_merge_loading: false,
            branch_merge_error: None,
            worktree_modal_open: false,
            worktree_loading: false,
            worktree_error: None,
            worktree_query: String::new(),
            worktree_entries: Vec::new(),
            worktree_selected_index: 0,
            worktree_matcher: Matcher::new(MatcherConfig::DEFAULT),
            commit_modal_open: false,
            commit_message: String::new(),
            commit_error: None,
            discard_target: None,
            remote_sync: None,
            review_loading: false,
            review_error: None,
            review_report: None,
            review_snapshot_id: None,
            review_provider_session_id: None,
            review_context_modal_open: false,
            review_extra_context: String::new(),
            review_summary_modal_open: false,
            review_summary_scroll: 0,
            review_request_id: 0,
            review_task: None,
            snackbar_notice: None,
            snackbar_generation: 0,
            status_message: None,
        }
    }
}
